# Generated by Django 3.2.6 on 2021-08-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exchRate_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbolCod_curr', models.CharField(max_length=5, verbose_name='Символьный код валюты')),
                ('amountCur', models.IntegerField(verbose_name='Количество валюты')),
                ('date_to', models.DateField(verbose_name='Начальная дата')),
                ('size_to', models.FloatField(verbose_name='Размер валюты в начальную дату')),
                ('date_from', models.DateField(verbose_name='Конечная дата')),
                ('size_from', models.FloatField(verbose_name='Размер валюты в конечную дату')),
                ('difference', models.FloatField(verbose_name='Разница в ₽')),
            ],
        ),
    ]
